
services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - 5000:5000
  
  frontend:
    build: 
      context: ./TodoApp
      args:
        VITE_API_URL: http://51.21.191.237:5000/api
    container_name: frontend
    restart: always
    ports:
      - 5173:5173
    depends_on: 
      - backend
    